apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-website
  namespace: my-website
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: ola-esan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-website
            port:
              number: 80
  - host: www.ola-esan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-website
            port:
              number: 80